### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by SaintPepsi** [Dev-CasperTheGhost/pastebin-api#3]
Hi,

I tried to use this package and I got the following error: `Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation`

I'm using Rollup/ES6.

I used your example for ES6.

I'm using it alongside  `svelte`

**Comment by Dev-CasperTheGhost** [comment]
Hey. Currently there isn't browser support, I'll look into browser support today

**Comment by Dev-CasperTheGhost** [comment]
Unfortunately I don't think there will be browser support since Pastebin doesn't allow requests from different origins in the browser. 

Tho, you could setup a small express server with the PasteClient to send the request to from your svelte application

**Comment by SaintPepsi** [comment]
Ahh Damn, Thanks for checking, I wasn't sure how it worked. Thanks anyway!

**Comment by Dev-CasperTheGhost** [comment]
No problem! I’ll close this issue, if you encounter another problem feel free to open another issue :)
