### ISSUE TITLE
Setting name property doesn't work, simply uploads with name "Untitled"

### ISSUE THREAD

**Issue by CrashRocks1419** [Dev-CasperTheGhost/pastebin-api#6]
This is the code for the encoding command in my discord bot:
```js
const purl = await pclient.createPaste({
  name: `${origString} encoded in WorstCode(TM)(R)(c)2069(lol)`,
  code: `${s5}`,
  expireDate: "N",
  publicity: 1,
});
```
`origString` and `s5` are the original string and final output, respectively. When I upload the output to pastebin with this package, the title is ignored and it uploads with the title of "Untitled" instead.

**Comment by Dev-CasperTheGhost** [comment]
Looks like the name limit is 100 characters. It might name it as `Untitled` since the name is longer than 100 characters

![image](https://user-images.githubusercontent.com/53900565/109465985-4bfda180-7a69-11eb-900d-1b1c8930d5a8.png)

**Comment by Dev-CasperTheGhost** [comment]
Let me know if changing the length of the name to less than 100 chars fixed it :)

**Comment by 2colours** [comment]
It didn't fix the problem but I issued a pull request that I think should fix it. Please check it out.
