### ISSUE TITLE
Any possible functionality to get Raw data from given URL?

### ISSUE THREAD

**Issue by MRDGH2821** [Dev-CasperTheGhost/pastebin-api#60]
Any possible functionality to get Raw data from given URL?

There's a module [pastebin-scraper](https://github.com/exoticchild-alt/pastebin-scraper) which fetches raw data (& other statistics) and returns it. 

I attempted to replicate this functionality (by forking & adding the relavent code in `pastebin-api`) but I can't understand how to test it.

Was there any existing way to fetch raw data simply by provided URL?

**Comment by MRDGH2821** [comment]
You may check out my fork & the test data.

The workflows/actions didn't give any errors. But I eed to see the output to understand if the `getRawPaste()` function (which i added) is working as expected or not.

**Comment by Dev-CasperTheGhost** [comment]
Feel free to open a PR with the changes, they look good. Will test them locally as well.

@MRDGH2821

**Comment by MRDGH2821** [comment]
Will this work for regular pastebin links too?

Or explictly the ID part has to be sent?

**Comment by Dev-CasperTheGhost** [comment]
The paste ID must be sent, it follows the API's spec.

**Comment by MRDGH2821** [comment]
Somehow the function is not working on my end as expected.

I want to get raw data, but this function returns `Bad API request, invalid api_user_key`

I'm using this library in my Discord bot. Beta version is throwing error when used at this [place](https://github.com/MRDGH2821/Discord-Ban-Utils-Bot/blob/c8a972dc91fbf2dd63a397f98d56fe7aa3f42b00/commands/import_ban_list.js#L50)

In my "stable" version of bot, it is working as expected.

The Link in question: https://pastebin.com/CHPktxqT
