### ISSUE TITLE
getRawPasteByKey() not working as expected

### ISSUE THREAD

**Issue by MRDGH2821** [Dev-CasperTheGhost/pastebin-api#62]
Somehow the function is not working on my end as expected.

I want to get raw data, but this function returns `Bad API request, invalid api_user_key`

I'm using this library in my Discord bot. The Beta version is throwing error when used at this [place](https://github.com/MRDGH2821/Discord-Ban-Utils-Bot/blob/c8a972dc91fbf2dd63a397f98d56fe7aa3f42b00/commands/import_ban_list.js#L50)

In my "stable" version of bot, it is working as expected.

The Link in question: https://pastebin.com/CHPktxqT

**Comment by MRDGH2821** [comment]
Also it would be nice to have [Documentation Index](https://github.com/MRDGH2821/pastebin-api/blob/main/docs/README.md#documentation) updated to include this function

**Comment by Dev-CasperTheGhost** [comment]
You can find the docs here: https://github.com/MRDGH2821/pastebin-api/blob/main/docs/README.md#get-raw-paste

**Comment by Dev-CasperTheGhost** [comment]
this response comes from the API itself, not from this library. So either an issue of the API or an invalid password/username.

**Comment by MRDGH2821** [comment]
My point is, I'm using the same dev API key, same username & same password

Using different pastebin library (better-pastebin) - I get the raw data.

Using this library - I get API error.

Which should not happen when everything is same (from dev API to pastebin link)

**Comment by MRDGH2821** [comment]
I will cross check things at my side tomorrow again before replying here
