### ISSUE TITLE
Add Pastbin "Password" and "Burn after read" 😄  

### ISSUE THREAD

**Issue by GeistFighter** [Dev-CasperTheGhost/pastebin-api#77]
Hey everyone,

My first question, does pastebin-api work under javascript?

And, can you add the two new functions of Pastebin if their API allows it?
![image](https://user-images.githubusercontent.com/42804270/150701170-16d01e65-97a3-4b23-98da-38d77d26da4f.png)

Thanks for everything!

**Comment by Dev-CasperTheGhost** [comment]
> My first question, does pastebin-api work under javascript?

Yes, ofcourse!

> And, can you add the two new functions of Pastebin if their API allows it?
image

Last time I checked these weren't documented yet, but I can take another look today.

**Comment by Dev-CasperTheGhost** [comment]
Looks like it's not supported by their API. The password field isn't documented either.

```txt
"Bad API request, Burn After Read paste can not be created via API"
```
